window.MATERIAL_REQUEST_MASTER = [
  { name: "12V SMPS PH-13/IOCL/KSRTC", type: "SMPS" },
  { name: "12V SMPS PH-8", type: "SMPS" },
  { name: "12V SMPS PH-9TO12/KSRTC", type: "SMPS" },
  { name: "24V SMPS PH-10", type: "SMPS" },
  { name: "5V SMPS PH-13/IOCL/KSRTC", type: "SMPS" },
  { name: "5V SMPS PH-9TO12/KSRTC", type: "SMPS" },
  { name: "5V TP SMPS", type: "SMPS" },
  { name: "ALISONIC CABLE-REGULAR", type: "PROBE CONNECTOR CABLE" },
  { name: "ALISONIC POWER-PCB", type: "PROBE PCB" },
  { name: "ALISONIC PH MS 2150", type: "PROBE" },
  { name: "BATTERY CHARGING PCB", type: "NEW FCC RBML" },
  { name: "BB CARD", type: "COPT/FCC" },
  { name: "BIG DIGIT 1,2", type: "EPS" },
  { name: "BIG DIGIT WITH DOT", type: "EPS" },
  { name: "BOS CARD PH-13/KSRTC", type: "BOS CARD" },
  { name: "BOS CARD PH-9TO12/KSRTC", type: "BOS CARD" },
  { name: "BOS KB", type: "OTHER" },
  { name: "BOS MONITOR", type: "OTHER" },
  { name: "BOS MOUSE", type: "OTHER" },
  { name: "CARD READER - RBML", type: "COPT/QROPT" },
  { name: "CNG SLAVE", type: "SLAVE" },
  { name: "CONTROL CARD", type: "EPS" },
  { name: "COPT KEYPAD", type: "COPT" },
  { name: "COPT LCD", type: "COPT" },
  { name: "COPT SMPS", type: "SMPS" },
  { name: "DC TO DC CONVERTER", type: "THERMAL PRINTER" },
  { name: "DIV1 PH-10", type: "THERMAL PRINTER" },
  { name: "DRILL MACHINE", type: "OTHER" },
  { name: "DRIVER MODULE", type: "THERMAL PRINTER" },
  { name: "DRV CARD", type: "EPS" },
  { name: "FCC CARD PH-13/KSRTC", type: "FCC" },
  { name: "FCC CARD PH-9TO12/KSRTC", type: "FCC" },
  { name: "FULL FCC", type: "FCC" },
  { name: "GATEWAY SLAVE", type: "COPT" },
  { name: "GSM MODULE", type: "GSM MODULE" },
  { name: "HP", type: "LAPTOP" },
  { name: "I/O CARD PH-13/KSRTC", type: "IO CARD" },
  { name: "I/O CARD PH-9TO12/KSRTC", type: "IO CARD" },
  { name: "INOPT 12V/9V SMPS", type: "SMPS" },
  { name: "INOPT DISPLAY", type: "INOPT" },
  { name: "INOPT INTERFACECARD", type: "INOPT" },
  { name: "IOT Class-1 with GSM", type: "IOT" },
  { name: "IOT Class-1 without SIM", type: "IOT" },
  { name: "JIO BP RTOS", type: "FCC RBML" },
  { name: "KEYPAD PH-10", type: "THERMAL PRINTER" },
  { name: "LAN - CRIMPING TOOL", type: "OTHER" },
  { name: "LAN TESTER", type: "OTHER" },
  { name: "LENOVO", type: "LAPTOP" },
  { name: "LIGHT SENSOR", type: "OTHER" },
  { name: "Li-on Battery", type: "OTHER" },
  { name: "LUG - CRIMPING TOOL", type: "OTHER" },
  { name: "MASTER CARD", type: "MASTER" },
  { name: "MB(+)BB CARD", type: "COPT" },
  { name: "MECHANICAL LOCK", type: "FCC" },
  { name: "MOTHER BOARD", type: "COPT" },
  { name: "NPL I/O CARD", type: "IO CARD" },
  { name: "OLD FCC CAP BOARD(JIO)", type: "FCC RBML" },
  { name: "OLD FCC RTOS(JIO)", type: "FCC RBML" },
  { name: "OLD FCC SMPS(JIO)", type: "SMPS" },
  { name: "OLD FCC-ISO 485(JIO)", type: "FCC RBML" },
  { name: "POS BOS", type: "FCC RBML" },
  { name: "QR OPT INTERFACECARD", type: "QR OPT" },
  { name: "QR OPT12V/9V SMPS", type: "SMPS" },
  { name: "QROPT DISPLAY", type: "QR OPT" },
  { name: "RBML 5V SMPS", type: "SMPS" },
  { name: "RBML 5V-10A SMPS", type: "SMPS" },
  { name: "RBML 5V-1A SMPS", type: "SMPS" },
  { name: "RBML BOS CARD", type: "FCC RBML" },
  { name: "RBML RF MASTER", type: "FCC RBML" },
  { name: "RF LOCK PCB PH-10/11", type: "FCC" },
  { name: "RF MASTER ETRX", type: "MASTER" },
  { name: "RF MASTER MGM", type: "MASTER" },
  { name: "RF SLAVE -MGM (HS)", type: "SLAVE" },
  { name: "RF SLAVE -MGM (COMPACT)", type: "SLAVE" },
  { name: "RF SLAVE PH-10", type: "SLAVE" },
  { name: "RF SLAVE-ETRX/PH-8", type: "SLAVE" },
  { name: "RF SLAVE-PYLON", type: "SLAVE" },
  { name: "ROUTER", type: "OTHER" },
  { name: "RS LOCK PCB PH-12/KSRTC", type: "FCC" },
  { name: "RS LOCK PCB PH-13/KSRTC", type: "FCC" },
  { name: "RTOS- NEW FCC", type: "FCC" },
  { name: "S2EN", type: "EPS" },
  { name: "SBEM AMP-PCB", type: "PROBE PCB" },
  { name: "SBEM MAIN-PCB", type: "PROBE PCB" },
  { name: "SBEM WARRENTY PCB", type: "PROBE PCB" },
  { name: "SBEM-2000", type: "PROBE" },
  { name: "SBEM-2250", type: "PROBE" },
  { name: "SBEM-2750", type: "PROBE" },
  { name: "SBEM-BIG (BLACK) CABLE", type: "PROBE CONNECTOR CABLE" },
  { name: "SBEM-PASSIVE-4CH", type: "BARRIER CARD" },
  { name: "SBEM-SMALL( BLUE) CABLE", type: "PROBE CONNECTOR CABLE" },
  { name: "SD Card", type: "OTHER" },
  { name: "SD Card Reader - BPCL", type: "OTHER" },
  { name: "SI BARRIER", type: "BARRIER CARD" },
  { name: "SI-XMT PCB", type: "PROBE PCB" },
  { name: "SI-XMT-2000", type: "PROBE" },
  { name: "SI-XMT-2250", type: "PROBE" },
  { name: "SI-XMT-2500", type: "PROBE" },
  { name: "SI-XMT-2750", type: "PROBE" },
  { name: "SMALL DIGIT 4,5", type: "EPS" },
  { name: "SPD", type: "OTHER" },
  { name: "SPI CARD", type: "QR OPT" },
  { name: "THERMAL PRINTER", type: "COPT/QROPT" },
  { name: "THERMAL PRINTER BODY", type: "THERMAL PRINTER" },
  { name: "USB TO SERIAL CONVERTER(RELCON)", type: "OTHER" },
  { name: "SI-DMP-2250", type: "PROBE" },
  { name: "SBEM HSD DENSITY FLOAT KIT", type: "PROBE" },
  { name: "IOT CLASS II WITHOUT SIM", type: "IOT" },
  { name: "MS PHASE SEPARATION FLOAT KIT", type: "PROBE" },
  { name: "AMC BOOK SET", type: "OTHER" },
  { name: "POWER PROTECTION PCB", type: "OTHER" },
  { name: "OLD FCC CABLE SET - RBML", type: "OTHER" },
  { name: "COPT CABLE SET", type: "OTHER" },
  { name: "SBEM-2000 WITH CABLE", type: "PROBE" },
  { name: "SBEM MS DENSITY FLOAT KIT", type: "PROBE" },
  { name: "SI-DMP-2000", type: "PROBE" },
  { name: "SBEM MS 2000 PHASE SEPARATION+DENSITY-BPCL", type: "PROBE" },
  { name: "NEW FCC CABLE SET - RBML", type: "OTHER" },
  { name: "LORA MASTER", type: "EPS" },
  { name: "HSD- ALISONIC FLOAT KIT", type: "FLOAT KIT" },
  { name: "RF SLAVE", type: "SLAVE" },
  { name: "HSD-SI-DMP-2260", type: "PROBE" },
  { name: "MS-SI-DMP-2000", type: "PROBE" },
  { name: "ALISONIC 2400 HSD", type: "PROBE" },
  { name: "WITH CABLE AND FLOAT KIT", type: "FLOAT KIT" },
  { name: "ALISONIC BARRIER", type: "BARRIER CARD" },
  { name: "SBEM ACTIVE BARRIER-4C", type: "BARRIER CARD" },
  { name: "CONTRACTOR PHASE13", type: "FCC" },
  { name: "SI-DMP-PROBE CONNECTOR", type: "PROBE" },
  { name: "FCC CABLE SET_PHASE-10", type: "CABLE" },
  { name: "LAPTOP RAM", type: "LAPTOP" }
];

window.MATERIAL_REQUEST_TYPES = [
  "Spare",
  "Project",
  "PO Basis",
  "Engineer Inventory",
  "Additional PH13",
  "Requiment given to HQO"
];

window.MATERIAL_STATUS_OPTIONS = [
  "Pending",
  "Requiment given to HQO",
  "In Process",
  "Dispatched",
  "In Transit",
  "Delivered"
];

window.DELIVERY_STATUS_OPTIONS = [
  "Pending",
  "In Transit",
  "Delivered",
  "Partially Delivered"
];
